services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongo_vol:/var/lib/mongo

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - redis_vol:/data

volumes:
  mongo_vol:
  redis_vol: